In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [7],
              [2]])
x

array([[0],
       [7],
       [2]])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([0])

In [10]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [9]:
x_t = x.T
x_t

array([[0, 7, 2]])

In [11]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [7]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[6],
              [1],
              [1]])

y_t = y.T
y_t

array([[6, 1, 1]])

In [12]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

3. lakukan soal nomor 2 menggunakan Pytorch dan Tensorflow

Pytorch


In [13]:
import torch as pt

In [14]:
x = pt.tensor([[0],
               [7],
               [2]])
x

tensor([[0],
        [7],
        [2]])

In [15]:
x_t = x.T
x_t

tensor([[0, 7, 2]])

In [16]:
x_t.shape

torch.Size([1, 3])

In [17]:
y = pt.tensor([[6],
               [1],
               [1]])
y

tensor([[6],
        [1],
        [1]])

In [18]:
y_t = y.T
y_t

tensor([[6, 1, 1]])

Tensorflow

In [19]:
import tensorflow as tf

In [20]:
x = tf.constant([[0],
                 [7],
                 [2]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [7],
       [2]], dtype=int32)>

In [21]:
x_t = tf.transpose(x)
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 7, 2]], dtype=int32)>

In [22]:
y = tf.constant([[6],
                 [1],
                 [1]])

In [23]:
y_t = tf.transpose(y)
y_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[6, 1, 1]], dtype=int32)>